"""empty message

Revision ID: 2b8fc0a7ac25
Revises: 2e048f1b9f25
Create Date: 2022-10-01 21:32:09.483720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8fc0a7ac25'
down_revision = '2e048f1b9f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('titles', sa.String(length=200), nullable=True))
    op.drop_column('files', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('files', 'titles')
    # ### end Alembic commands ###
