"""empty message

Revision ID: 2e048f1b9f25
Revises: 635407c6eec4
Create Date: 2022-10-01 21:30:24.510209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e048f1b9f25'
down_revision = '635407c6eec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(length=100), nullable=True))
    op.drop_column('files', 'url_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
