"""empty message

Revision ID: 635407c6eec4
Revises: 
Create Date: 2022-10-01 21:29:50.366935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635407c6eec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url_path', sa.String(length=100), nullable=True))
    op.drop_column('files', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('files', 'url_path')
    # ### end Alembic commands ###
