"""empty message

Revision ID: d0fb716d3d05
Revises: 626530312ac7
Create Date: 2022-10-01 21:43:04.852891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fb716d3d05'
down_revision = '626530312ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('paths', sa.String(), nullable=True))
    op.add_column('files', sa.Column('titles', sa.String(), nullable=True))
    op.drop_column('files', 'path')
    op.drop_column('files', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('files', 'titles')
    op.drop_column('files', 'paths')
    # ### end Alembic commands ###
