"""empty message

Revision ID: d156fda279bd
Revises: d0fb716d3d05
Create Date: 2022-10-01 21:43:18.788964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd156fda279bd'
down_revision = 'd0fb716d3d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('files', 'paths')
    op.drop_column('files', 'titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('titles', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('paths', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('files', 'title')
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
