name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: 'Create env file'
      working-directory: ./backend
      run: |
          echo "${{ secrets.QUEUE_ENV }}" > .env/queue.env
          echo "${{ secrets.API_ENV }}" > .env/api.env

    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./backend
      run: |
        docker-compose up --build 
